# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 1
[[main]]
    name = "Installation"
    url = "/installation/"
    weight = 2
[[main]]
    name = "Tutorials"
    url = "/start/"
    weight = 3
[[main]]
    name = "Book"
    url = "https://book.tidymass.org/"
    weight = 4
[[main]]
    name = "More"
    url = "/more/"
    weight = 5
[[main]]
    name = "Blog/News"
    url = "/blog/"
    weight = 6
[[main]]
    name = "Contact"
    url = "/contact/"
    weight = 7
[[main]]
    pre = "<i class=\"fab fa-github fa-lg\"></i>"
    url = "https://github.com/tidymass/"
    weight = 7
    

